name: Upload 

on:
  pull_request:
    branches:
      - '*'

jobs:
  deploy:
    name: Upload sn platform image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup ACK environments
      run: |
        sudo apt update
        sudo snap install yq
        .ci/download_image.sh sn-platform-1.3.1

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'sn-platform-1.3.1.tar' 
        DEST_DIR: 'sn-platform-2.3.1'